baseURL = '/'
languageCode = 'en-us'
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
title = 'Oyster Data'
theme = 'hugo-winston-theme'
#disableKinds = ["header"]

[params]
	showAuthorOnHomepage = false
	showAuthorOnPosts = false
	showPostsOnHomepage = false
	addDot = true
	addFrame = true
	highlightColor = '#006994'
	baseColor = "#ffffff"
	baseOffsetColor = "#eaeaea"
	headingColor = "#1c1b1d"
	textColor = "#4e5157"
	dotColor = "#89a9ee"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1    
#  [[menu.main]]
#    name = "Tags"
#    identifier = "tags"
#    weight = 300
#    url = "/tags/"